In [1]:
import Pkg
import Serialization
Pkg.add("Combinatorics")
Pkg.add("Primes")
Pkg.add("BenchmarkTools")
Pkg.add("Transducers")
using Combinatorics
using Primes
using BenchmarkTools
using Transducers

include("header.jl")

import Base.Iterators

savevar(file_path::String, a) = Serialization.serialize(file_path, a)
loadvar(file_path::String) = Serialization.deserialize(file_path)

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.10/Project.toml`
  No Changes to `~/.julia/environments/v1.10/Manifest.toml`


loadvar (generic function with 1 method)

In [24]:
println(iscostas([1,2,3]))
println(iscostas([1,2]))
println(iscostas([1,2,4,3]))
println(iscostas([4,2,3,1]))

false
true
true
false


In [25]:
welch(11)

4-element Vector{Vector{Integer}}:
 [2, 4, 8, 5, 10, 9, 7, 3, 6, 1]
 [6, 3, 7, 9, 10, 5, 8, 4, 2, 1]
 [7, 5, 2, 3, 10, 4, 6, 9, 8, 1]
 [8, 9, 6, 4, 10, 3, 2, 5, 7, 1]

In [26]:
lempel(11)

4-element Vector{Vector{Integer}}:
 [5, 3, 2, 7, 1, 8, 4, 6, 9]
 [1, 4, 6, 2, 9, 3, 8, 7, 5]
 [2, 1, 5, 8, 3, 9, 7, 4, 6]
 [4, 6, 3, 1, 7, 2, 5, 9, 8]

In [27]:
lempel(11) |> Filter(iscostas) |> collect

4-element Vector{Vector{Integer}}:
 [5, 3, 2, 7, 1, 8, 4, 6, 9]
 [1, 4, 6, 2, 9, 3, 8, 7, 5]
 [2, 1, 5, 8, 3, 9, 7, 4, 6]
 [4, 6, 3, 1, 7, 2, 5, 9, 8]

In [3]:
for n in 1:10
    # out = 1:n |> permutations |> Filter(iscostas) |> tcollect
    file_path = "costas_$(n)x$(n).dat"
    out = loadvar(file_path)
    #savevar(file_path, out)
    println("$(file_path) has $(length(out)) arrays.")
end

costas_1x1 = loadvar("costas_1x1.dat")
costas_2x2 = loadvar("costas_2x2.dat")
costas_3x3 = loadvar("costas_3x3.dat")
costas_4x4 = loadvar("costas_4x4.dat")
costas_5x5 = loadvar("costas_5x5.dat")
costas_6x6 = loadvar("costas_6x6.dat")
costas_7x7 = loadvar("costas_7x7.dat")
costas_8x8 = loadvar("costas_8x8.dat")
costas_9x9 = loadvar("costas_9x9.dat")
costas_10x10 = loadvar("costas_10x10.dat")
costas_11x11 = loadvar("costas_11x11.dat")
println("costas_11x11 has $(length(costas_11x11)) arrays.")
costas_12x12 = loadvar("costas_12x12.dat")
println("costas_12x12 has $(length(costas_12x12)) arrays.")
costas_13x13 = loadvar("costas_13x13.dat")
println("costas_13x13 has $(length(costas_13x13)) arrays.")

costas_1x1.dat has 1 arrays.
costas_2x2.dat has 2 arrays.
costas_3x3.dat has 4 arrays.
costas_4x4.dat has 12 arrays.
costas_5x5.dat has 40 arrays.
costas_6x6.dat has 116 arrays.
costas_7x7.dat has 200 arrays.
costas_8x8.dat has 444 arrays.
costas_9x9.dat has 760 arrays.
costas_10x10.dat has 2160 arrays.
costas_11x11 has 4368 arrays.
costas_12x12 has 7852 arrays.
costas_13x13 has 12828 arrays.


In [65]:
for n in 1:10
    out = 2:n |> permutations |> Filter(Base.Fix2(iscostas, asterisk_predicate)) |> tcollect
    file_path = "costas_$(n)x$(n + 1).dat"
    #savevar(file_path, out)
    println("$(file_path) has $(size(out, 1)) arrays.")
end

costas_1x2 = loadvar("costas_1x2.dat")
costas_2x3 = loadvar("costas_2x3.dat")
costas_3x4 = loadvar("costas_3x4.dat")
costas_4x5 = loadvar("costas_4x5.dat")
costas_5x6 = loadvar("costas_5x6.dat")
costas_6x7 = loadvar("costas_6x7.dat")
costas_7x8 = loadvar("costas_7x8.dat")
costas_8x9 = loadvar("costas_8x9.dat")
costas_9x10 = loadvar("costas_9x10.dat")
costas_10x11 = loadvar("costas_10x11.dat")

costas_1x2.dat has 1 arrays.
costas_2x3.dat has 1 arrays.
costas_3x4.dat has 2 arrays.
costas_4x5.dat has 4 arrays.
costas_5x6.dat has 12 arrays.
costas_6x7.dat has 40 arrays.
costas_7x8.dat has 116 arrays.
costas_8x9.dat has 200 arrays.
costas_9x10.dat has 444 arrays.
costas_10x11.dat has 760 arrays.


760-element Vector{Vector{Int64}}:
 [2, 3, 7, 5, 10, 9, 6, 8, 4]
 [2, 3, 7, 9, 6, 4, 10, 5, 8]
 [2, 3, 7, 9, 6, 5, 10, 8, 4]
 [2, 3, 7, 10, 6, 4, 9, 8, 5]
 [2, 3, 8, 6, 10, 7, 9, 5, 4]
 [2, 3, 8, 7, 10, 5, 9, 6, 4]
 [2, 3, 9, 5, 10, 8, 7, 4, 6]
 [2, 3, 10, 5, 8, 4, 9, 7, 6]
 [2, 3, 10, 7, 6, 4, 9, 5, 8]
 [2, 3, 10, 7, 9, 5, 4, 8, 6]
 [2, 3, 10, 9, 5, 7, 4, 8, 6]
 [2, 4, 8, 5, 10, 9, 7, 3, 6]
 [2, 4, 9, 8, 3, 10, 6, 7, 5]
 ⋮
 [10, 8, 4, 7, 2, 3, 5, 9, 6]
 [10, 9, 2, 3, 7, 5, 8, 4, 6]
 [10, 9, 2, 5, 3, 7, 8, 4, 6]
 [10, 9, 2, 5, 6, 8, 3, 7, 4]
 [10, 9, 2, 7, 4, 8, 3, 5, 6]
 [10, 9, 3, 7, 2, 4, 5, 8, 6]
 [10, 9, 4, 5, 2, 7, 3, 6, 8]
 [10, 9, 4, 6, 2, 5, 3, 7, 8]
 [10, 9, 5, 2, 6, 8, 3, 4, 7]
 [10, 9, 5, 3, 6, 7, 2, 4, 8]
 [10, 9, 5, 3, 6, 8, 2, 7, 4]
 [10, 9, 5, 7, 2, 3, 6, 4, 8]

In [28]:
@btime 1:7 |> permutations |> Filter(iscostas) |> tcollect
@btime 1:7 |> permutations |> Filter(iscostas) |> tcollect

  1.473 ms (47207 allocations: 4.12 MiB)
  1.476 ms (47207 allocations: 4.12 MiB)


200-element Vector{Vector{Int64}}:
 [1, 2, 6, 4, 7, 3, 5]
 [1, 2, 7, 4, 6, 5, 3]
 [1, 2, 7, 5, 4, 6, 3]
 [1, 3, 6, 2, 7, 4, 5]
 [1, 3, 6, 2, 7, 5, 4]
 [1, 3, 7, 6, 4, 5, 2]
 [1, 4, 2, 6, 7, 3, 5]
 [1, 4, 2, 7, 6, 3, 5]
 [1, 4, 5, 3, 7, 6, 2]
 [1, 4, 5, 7, 2, 6, 3]
 [1, 4, 6, 5, 3, 7, 2]
 [1, 5, 3, 6, 7, 2, 4]
 [1, 5, 7, 2, 3, 6, 4]
 ⋮
 [7, 3, 5, 2, 1, 6, 4]
 [7, 4, 2, 3, 5, 1, 6]
 [7, 4, 3, 1, 6, 2, 5]
 [7, 4, 3, 5, 1, 2, 6]
 [7, 4, 6, 1, 2, 5, 3]
 [7, 4, 6, 2, 1, 5, 3]
 [7, 5, 1, 2, 4, 3, 6]
 [7, 5, 2, 6, 1, 3, 4]
 [7, 5, 2, 6, 1, 4, 3]
 [7, 6, 1, 3, 4, 2, 5]
 [7, 6, 1, 4, 2, 3, 5]
 [7, 6, 2, 4, 1, 5, 3]

In [29]:
@btime 1:7 |> permutations |> Filter(iscostasdbg) |> tcollect
@btime 1:7 |> permutations |> Filter(iscostasdbg) |> tcollect

  1.459 ms (50096 allocations: 4.31 MiB)
  1.463 ms (50096 allocations: 4.31 MiB)


788-element Vector{Vector{Int64}}:
 [1, 2, 3, 5, 7, 6, 4]
 [1, 2, 3, 6, 4, 5, 7]
 [1, 2, 4, 3, 6, 7, 5]
 [1, 2, 4, 6, 3, 7, 5]
 [1, 2, 4, 6, 5, 3, 7]
 [1, 2, 4, 7, 5, 6, 3]
 [1, 2, 4, 7, 6, 3, 5]
 [1, 2, 4, 7, 6, 5, 3]
 [1, 2, 5, 3, 7, 6, 4]
 [1, 2, 5, 4, 6, 7, 3]
 [1, 2, 5, 7, 3, 6, 4]
 [1, 2, 5, 7, 4, 3, 6]
 [1, 2, 6, 3, 4, 5, 7]
 ⋮
 [7, 6, 3, 1, 4, 5, 2]
 [7, 6, 3, 1, 5, 2, 4]
 [7, 6, 3, 4, 2, 1, 5]
 [7, 6, 3, 5, 1, 2, 4]
 [7, 6, 4, 1, 2, 3, 5]
 [7, 6, 4, 1, 2, 5, 3]
 [7, 6, 4, 1, 3, 2, 5]
 [7, 6, 4, 2, 3, 5, 1]
 [7, 6, 4, 2, 5, 1, 3]
 [7, 6, 4, 5, 2, 1, 3]
 [7, 6, 5, 2, 4, 3, 1]
 [7, 6, 5, 3, 1, 2, 4]

In [15]:
println("From costas_1x2:")
checklempel(costas_1x2,3)
println("From costas_3x4:")
checklempel(costas_3x4,5)
println("From costas_5x6:")
checklempel(costas_5x6,7)
println("From costas_9x10:")
checklempel(costas_9x10,11)

From costas_1x2:
Any[1, '*']
Any['*', 1]
From costas_3x4:
Any[1, 2, '*', 3]
Any[1, 3, 2, '*']
Any[2, 1, 3, '*']
Any[2, '*', 1, 3]
Any[3, 1, '*', 2]
Any[3, '*', 2, 1]
Any['*', 2, 3, 1]
Any['*', 3, 1, 2]
From costas_5x6:
Any[2, 3, 5, '*', 1, 4]
Any[3, 1, '*', 5, 2, 4]
Any[4, 1, '*', 5, 3, 2]
Any[4, 2, 5, '*', 1, 3]
Any[5, 2, 4, 3, 1, '*']
Any[5, 3, 2, 4, 1, '*']
Any['*', 1, 3, 4, 2, 5]
Any['*', 1, 4, 2, 3, 5]
From costas_9x10:
Any[1, 4, 6, 2, 9, 3, 8, 7, 5, '*']
Any[1, 7, 2, 3, 5, '*', 9, 6, 4, 8]
Any[2, 1, 5, 8, 3, 9, 7, 4, 6, '*']
Any[2, 5, 9, 8, '*', 4, 6, 3, 1, 7]
Any[3, 8, 5, 1, 2, '*', 6, 4, 7, 9]
Any[3, 8, 7, 5, '*', 1, 4, 6, 2, 9]
Any[4, 6, 3, 1, 7, 2, 5, 9, 8, '*']
Any[5, 3, 2, 7, 1, 8, 4, 6, 9, '*']
Any[7, 1, 3, 6, 4, '*', 8, 9, 5, 2]
Any[8, 4, 6, 9, '*', 5, 3, 2, 7, 1]
Any[9, 2, 6, 4, 1, '*', 5, 7, 8, 3]
Any[9, 7, 4, 6, '*', 2, 1, 5, 8, 3]
Any['*', 5, 7, 8, 3, 9, 2, 6, 4, 1]
Any['*', 6, 4, 7, 9, 3, 8, 5, 1, 2]
Any['*', 8, 9, 5, 2, 7, 1, 3, 6, 4]
Any['*', 9, 6, 4, 8, 1, 7, 2, 3

In [16]:
function checkwelch(costas::Vector{Vector{Integer}}, prime::Integer)
    all(all(w == lst || isrotated(w, lst) || isrotated(w, reverse(lst)) for w in welch(prime)) for lst in costas)
end

checkwelch (generic function with 1 method)

In [17]:
println("From costas_2x2:", checkwelch(costas_2x2,3))
println("From costas_4x4:", checkwelch(costas_4x4,5))
println("From costas_6x6:", checkwelch(costas_6x6,7))
println("From costas_10x10:", checkwelch(costas_10x10,11))

LoadError: MethodError: no method matching checkwelch(::Vector{Vector{Int64}}, ::Int64)

Closest candidates are:
  checkwelch(::Vector{Vector{Integer}}, ::Integer)
   @ Main In[16]:1


In [59]:
function filterwelchs(costas, prime)
    filter(lst -> all(!isrotated(lst, w) && !isrotated(lst, reverse(w)) for w in welch(prime)), costas)
end
filterwelchs(costas_4x4, 5)

4-element Vector{Vector{Int64}}:
 [1, 4, 2, 3]
 [2, 3, 1, 4]
 [3, 2, 4, 1]
 [4, 1, 3, 2]

In [61]:
function issubarray(lhs::Vector, rhs::Vector)::Bool
    lhs .|> Base.Fix1(findindex, rhs) |> issorted
end

issubarray (generic function with 2 methods)

In [64]:
for arr in filterwelchs(costas_10x10, 11)
    for l in lempel(11)
        if issubarray(l, arr)
            println("$l $arr")
        end
    end
end

Integer[1, 4, 6, 2, 9, 3, 8, 7, 5] [10, 1, 4, 6, 2, 9, 3, 8, 7, 5]
Integer[2, 1, 5, 8, 3, 9, 7, 4, 6] [10, 2, 1, 5, 8, 3, 9, 7, 4, 6]
Integer[4, 6, 3, 1, 7, 2, 5, 9, 8] [10, 4, 6, 3, 1, 7, 2, 5, 9, 8]
Integer[5, 3, 2, 7, 1, 8, 4, 6, 9] [10, 5, 3, 2, 7, 1, 8, 4, 6, 9]


In [65]:
length(filterwelchs(costas_10x10, 11))

2144

In [25]:
# /*
#  * Complexity: O(n^3)
#  */
# template <class T> fn build_all_naive(Vec<T> const& vec, T x) -> Vec<Vec<T>> {
#     var out = Vec<Vec<T>>();
#     for (Size i = 0; i < vec.size(); ++i) {
#         var lst2 = vec;
#         lst2.insert(lst2.begin() + i, x);
#         if (is_costas(lst2))
#             out.push_back(lst2);
#     }
#     return out;
# }

function buildallnaive(vec::Vector{T}, x::T)::Vector{Vector{T}} where T
    out = []
    for i in 1:length(vec)
        lst2 = copy(vec)
        insert!(lst2, i, x)
        if iscostas(lst2)
            push!(out,lst2)
        end
    end
    out
end

buildallnaive (generic function with 1 method)

In [63]:
for v in welch(17)
    println(buildallnaive(v,17))
end

Vector{Integer}[]
Vector{Integer}[]
Vector{Integer}[]
Vector{Integer}[]
Vector{Integer}[]
Vector{Integer}[]
Vector{Integer}[]
Vector{Integer}[]


In [57]:
primes(40)

12-element Vector{Int64}:
  2
  3
  5
  7
 11
 13
 17
 19
 23
 29
 31
 37

In [34]:
out = [[1,2],[2,1]]
for i ∈ 3:20
    out = [buildallnaive(vec,i) |> flatten for vec in out]
    println(out)
end

[3, 1, 2]
[1, 3, 2]
[2, 3, 1]
[[3, 1, 2, 1, 3, 2], [2, 3, 1]]
[2, 4, 3, 1]
[Int64[], [2, 4, 3, 1]]
[5, 2, 4, 3, 1]
[Int64[], [5, 2, 4, 3, 1]]
[5, 2, 4, 3, 6, 1]
[Int64[], [5, 2, 4, 3, 6, 1]]
[Int64[], Int64[]]
[Int64[], Int64[]]
[Int64[], Int64[]]
[Int64[], Int64[]]
[Int64[], Int64[]]
[Int64[], Int64[]]
[Int64[], Int64[]]
[Int64[], Int64[]]
[Int64[], Int64[]]
[Int64[], Int64[]]
[Int64[], Int64[]]
[Int64[], Int64[]]
[Int64[], Int64[]]
[Int64[], Int64[]]


In [31]:
function flatten(vec::Vector{Vector{T}})::Vector{T} where T
    out = []
    for v in vec
        println(v)
        out = vcat(out,v)
    end
    out
end

flatten (generic function with 1 method)

In [32]:
flatten([[1,2],[2,3]])

[1, 2]
[2, 3]


4-element Vector{Int64}:
 1
 2
 2
 3

In [89]:
@btime 1:8 |> permutations |> Filter(iscostas) |> tcollect
@btime 1:8 |> permutations |> tcollect |> Filter(iscostas) |> tcollect

  12.701 ms (369811 allocations: 34.37 MiB)
  13.263 ms (369822 allocations: 35.17 MiB)


444-element Vector{Vector{Int64}}:
 [1, 2, 5, 7, 6, 4, 8, 3]
 [1, 2, 8, 6, 3, 5, 4, 7]
 [1, 3, 6, 2, 7, 8, 5, 4]
 [1, 3, 6, 7, 5, 2, 8, 4]
 [1, 3, 6, 7, 5, 4, 8, 2]
 [1, 3, 8, 6, 7, 2, 5, 4]
 [1, 4, 2, 8, 7, 3, 5, 6]
 [1, 4, 5, 3, 7, 6, 8, 2]
 [1, 4, 5, 7, 6, 3, 8, 2]
 [1, 5, 3, 8, 7, 4, 6, 2]
 [1, 5, 4, 7, 2, 8, 6, 3]
 [1, 5, 6, 3, 8, 7, 2, 4]
 [1, 5, 6, 8, 3, 2, 7, 4]
 ⋮
 [8, 4, 3, 6, 1, 2, 7, 5]
 [8, 4, 5, 2, 7, 1, 3, 6]
 [8, 4, 6, 1, 2, 5, 3, 7]
 [8, 5, 4, 2, 3, 6, 1, 7]
 [8, 5, 4, 6, 2, 3, 1, 7]
 [8, 5, 7, 1, 2, 6, 4, 3]
 [8, 6, 1, 3, 2, 7, 4, 5]
 [8, 6, 3, 2, 4, 5, 1, 7]
 [8, 6, 3, 2, 4, 7, 1, 5]
 [8, 6, 3, 7, 2, 1, 4, 5]
 [8, 7, 1, 3, 6, 4, 5, 2]
 [8, 7, 4, 2, 3, 5, 1, 6]

In [12]:
push!

push! (generic function with 27 methods)

In [74]:
function iscostashelper2(lst::Vector{T}, f::Function, n::Integer)::Bool where T
    all(begin
        seen::Vector{Bool} = zeros(Bool, 2 * n)
        all(begin
                result = f(lst[i+k],lst[i],n)
                prev = seen[result]
                seen[result] = true
                !prev
            end for i ∈ 1:(n - k))
        end for k ∈ 1:n)
end

iscostashelper2 (generic function with 1 method)

In [76]:
iscostashelper2([1,2,3], (x,y,n) -> x - y + n, 3)

false

In [87]:
1:8 |> collect

8-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8

In [85]:
costas_2x3

6-element Vector{Vector{Any}}:
 [1, 2, '*']
 [1, '*', 2]
 [2, 1, '*']
 [2, '*', 1]
 ['*', 1, 2]
 ['*', 2, 1]

In [4]:
costas_4x4

12-element Vector{Vector{Int64}}:
 [1, 2, 4, 3]
 [1, 3, 4, 2]
 [1, 4, 2, 3]
 [2, 1, 3, 4]
 [2, 3, 1, 4]
 [2, 4, 3, 1]
 [3, 1, 2, 4]
 [3, 2, 4, 1]
 [3, 4, 2, 1]
 [4, 1, 3, 2]
 [4, 2, 1, 3]
 [4, 3, 1, 2]

In [6]:
lst = copy(costas_4x4)

12-element Vector{Vector{Int64}}:
 [1, 2, 4, 3]
 [1, 3, 4, 2]
 [1, 4, 2, 3]
 [2, 1, 3, 4]
 [2, 3, 1, 4]
 [2, 4, 3, 1]
 [3, 1, 2, 4]
 [3, 2, 4, 1]
 [3, 4, 2, 1]
 [4, 1, 3, 2]
 [4, 2, 1, 3]
 [4, 3, 1, 2]

In [8]:
push!(lst,[3])

13-element Vector{Vector{Int64}}:
 [1, 2, 4, 3]
 [1, 3, 4, 2]
 [1, 4, 2, 3]
 [2, 1, 3, 4]
 [2, 3, 1, 4]
 [2, 4, 3, 1]
 [3, 1, 2, 4]
 [3, 2, 4, 1]
 [3, 4, 2, 1]
 [4, 1, 3, 2]
 [4, 2, 1, 3]
 [4, 3, 1, 2]
 [3]

In [9]:
costas_4x4

12-element Vector{Vector{Int64}}:
 [1, 2, 4, 3]
 [1, 3, 4, 2]
 [1, 4, 2, 3]
 [2, 1, 3, 4]
 [2, 3, 1, 4]
 [2, 4, 3, 1]
 [3, 1, 2, 4]
 [3, 2, 4, 1]
 [3, 4, 2, 1]
 [4, 1, 3, 2]
 [4, 2, 1, 3]
 [4, 3, 1, 2]

In [27]:
lst = lempel(31)[1]

29-element Vector{Integer}:
  9
 27
 20
 11
 25
  6
 21
 19
  1
 28
  4
 13
 12
  ⋮
 16
  8
  3
  7
 26
 29
 15
  5
 22
  2
 10
 23

In [28]:
for i in 1:length(lst)
    if lst[i] == i
        println(lst[i], ' ', i)
    end
end

6 6


In [25]:

push!(lst, 30)

30-element Vector{Integer}:
  9
 27
 20
 11
 25
  6
 21
 19
  1
 28
  4
 13
 12
  ⋮
  8
  3
  7
 26
 29
 15
  5
 22
  2
 10
 23
 30

In [30]:
iscostas([4,5,3,1,2])

false

In [32]:
primes(40)

12-element Vector{Int64}:
  2
  3
  5
  7
 11
 13
 17
 19
 23
 29
 31
 37

In [36]:
lst = lempel(37)[1]

35-element Vector{Integer}:
 18
  8
 14
 31
 27
 30
 22
  2
 32
 11
 10
 28
 15
  ⋮
 34
 17
 19
  5
 12
 33
  6
  4
  9
 29
 24
 35

In [44]:
lst = lempel(37)[1]
lst = [lst[i] for i in 1:(length(lst) - 1)]
lst[24] = lst[34]
lst = [lst[i] for i in 1:(length(lst) - 1)]
lst[29] = lst[33]
lst = [lst[i] for i in 1:(length(lst) - 1)]
iscostas(lst)

false

In [46]:
for p in primes(70)
    println("$p: $(length(lempel(p)))")
end

2: 1
3: 1
5: 2
7: 2
11: 4
13: 4
17: 8
19: 6
23: 10
29: 12
31: 8
37: 12
41: 16
43: 12
47: 22
53: 24
59: 28
61: 16
67: 20


In [2]:
function telephone(n)
    n <= 1 ? 1 : telephone(n-1) + (n - 1) * telephone(n - 2)
end

telephone (generic function with 1 method)

In [48]:
telephone(32)

4034315351021199616

In [4]:
for i ∈ 1:10
    println(telephone(i))
end

1
2
4
10
26
76
232
764
2620
9496


In [8]:
welch(37)

12-element Vector{Vector{Integer}}:
 [2, 4, 8, 16, 32, 27, 17, 34, 31, 25  …  6, 12, 24, 11, 22, 7, 14, 28, 19, 1]
 [5, 25, 14, 33, 17, 11, 18, 16, 6, 30  …  31, 7, 35, 27, 24, 9, 8, 3, 15, 1]
 [13, 21, 14, 34, 35, 11, 32, 9, 6, 4  …  31, 33, 22, 27, 18, 12, 8, 30, 20, 1]
 [15, 3, 8, 9, 24, 27, 35, 7, 31, 21  …  6, 16, 18, 11, 17, 33, 14, 25, 5, 1]
 [17, 30, 29, 12, 19, 27, 15, 33, 6, 28  …  31, 9, 5, 11, 2, 34, 23, 21, 24, 1]
 [18, 28, 23, 7, 15, 11, 13, 12, 31, 3  …  6, 34, 20, 27, 5, 16, 29, 4, 35, 1]
 [19, 28, 14, 7, 22, 11, 24, 12, 6, 3  …  31, 34, 17, 27, 32, 16, 8, 4, 2, 1]
 [20, 30, 8, 12, 18, 27, 22, 33, 31, 28  …  6, 9, 32, 11, 35, 34, 14, 21, 13, 1]
 [22, 3, 29, 9, 13, 27, 2, 7, 6, 21  …  31, 16, 19, 11, 20, 33, 23, 25, 32, 1]
 [24, 21, 23, 34, 2, 11, 5, 9, 31, 4  …  6, 33, 15, 27, 19, 12, 29, 30, 17, 1]
 [32, 25, 23, 33, 20, 11, 19, 16, 31, 30  …  6, 7, 2, 27, 13, 9, 29, 3, 22, 1]
 [35, 4, 29, 16, 5, 27, 20, 34, 6, 25  …  31, 12, 13, 11, 15, 7, 23, 28, 18, 1]

In [9]:
iscostas([4,6,7,2,8,1,5,3])

true

In [46]:
function ts(n::Integer)::Vector{Vector{Integer}}
    out = [[1]]
    for i ∈ 1:n
        new_out = []
        for vec ∈ out
            println(vec)
            verts = findverts(vec)
            println(verts)
            for vert ∈ verts
                c = swapidx([copy(vec);[i+1]], vert, i)
                push!(new_out, c)
                println("$new_out, $i")
            end
            push!(new_out, [copy(vec);[i+1]])
        end
        new_out
        out = new_out
    end
    out
end

ts (generic function with 1 method)

In [47]:
ts(2)

[1]
Any[1]
Any[[1, 2]], 1
[1, 2]
Any[1, 2]
Any[[2, 1, 3]], 2
Any[[2, 1, 3], [1, 2, 3]], 2
[1, 2]
Any[1, 2]
Any[[2, 1, 3], [1, 2, 3], [1, 2, 3], [2, 1, 3]], 2
Any[[2, 1, 3], [1, 2, 3], [1, 2, 3], [2, 1, 3], [1, 2, 3]], 2


6-element Vector{Vector{Integer}}:
 [2, 1, 3]
 [1, 2, 3]
 [1, 2, 3]
 [2, 1, 3]
 [1, 2, 3]
 [1, 2, 3]

In [38]:
[1]

[1,2]
[2,1]

[1,2,3]
[3,2,1]
[1,3,2]
[2,1,3]

[4,2,3,1]
[1,4,3,2]
[1,2,4,3]
[1,2,3,4]
[3,4,1,2]
[3,2,1,4]
[4,3,2,1]
[1,3,2,4]
[2,1,4,3]
[2,1,3,4]

4-element Vector{Int64}:
 2
 1
 3
 4

In [18]:
function findverts(vec::Vector)::Vector
    out = []
    for i in 1:length(vec)
        if vec[i] == i
            push!(out, i)
        end
    end
    out
end

findverts (generic function with 2 methods)

In [12]:
function swapidx(vec::Vector{T}, i::Integer, j::Integer)::Vector{T} where T
    tmp = vec[i]
    vec[i] = vec[j]
    vec[j] = tmp
    vec
end

swapidx (generic function with 1 method)

In [32]:
swapidx([1,2,3],1,2)

3-element Vector{Int64}:
 2
 1
 3

In [33]:
a = [1,2,3]
b = [4,5,6]
[a;b]

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [49]:
welch(11)

4-element Vector{Vector{Integer}}:
 [2, 4, 8, 5, 10, 9, 7, 3, 6, 1]
 [6, 3, 7, 9, 10, 5, 8, 4, 2, 1]
 [7, 5, 2, 3, 10, 4, 6, 9, 8, 1]
 [8, 9, 6, 4, 10, 3, 2, 5, 7, 1]

In [22]:
welch(7)

2-element Vector{Vector{Integer}}:
 [3, 2, 6, 4, 5, 1]
 [5, 4, 6, 2, 3, 1]

In [7]:
iscostas([6,2,1,4,5,3])

true

In [8]:
lempel(11)

4-element Vector{Vector{Integer}}:
 [5, 3, 2, 7, 1, 8, 4, 6, 9]
 [1, 4, 6, 2, 9, 3, 8, 7, 5]
 [2, 1, 5, 8, 3, 9, 7, 4, 6]
 [4, 6, 3, 1, 7, 2, 5, 9, 8]

In [15]:
iscostas([10,3,4,6,2,7,1,9,8,5,10,3,4,6,2,7,1,9,8,5])

false

In [19]:
iscostas([5, 3, 2, 7, 1, 8, 4, 6, 9, '*', 5, 3, 2, 7, 1, 8, 4, 6, 9], asterisk_predicate)

false

In [21]:
iscostas([2,4,3,5])

false

In [25]:
for i in 1:11
    pow = i
    for _ in 1:10
        print(pow % 11, ' ')
        pow *= i
    end
    println()
end

1 1 1 1 1 1 1 1 1 1 
2 4 8 5 10 9 7 3 6 1 
3 9 5 4 1 3 9 5 4 1 
4 5 9 3 1 4 5 9 3 1 
5 3 4 9 1 5 3 4 9 1 
6 3 7 9 10 5 8 4 2 1 
7 5 2 3 10 4 6 9 8 1 
8 9 6 4 10 3 2 5 7 1 
9 4 3 5 1 9 4 3 5 1 
10 1 10 1 10 1 10 1 10 1 
0 0 0 0 0 0 0 0 0 0 


In [3]:
welch(11)

4-element Vector{Vector{Integer}}:
 [2, 4, 8, 5, 10, 9, 7, 3, 6, 1]
 [6, 3, 7, 9, 10, 5, 8, 4, 2, 1]
 [7, 5, 2, 3, 10, 4, 6, 9, 8, 1]
 [8, 9, 6, 4, 10, 3, 2, 5, 7, 1]

In [2]:
lempel(7)

2-element Vector{Vector{Integer}}:
 [5, 3, 2, 4, 1]
 [5, 2, 4, 3, 1]

In [31]:
lempel(7)

2-element Vector{Vector{Integer}}:
 [5, 3, 2, 4, 1]
 [5, 2, 4, 3, 1]

In [30]:
iscostas([[6, 10, 5, 7, 3, 1, 4, 9, 8, 2, 11]; '*'], asterisk_predicate)

true

In [22]:
lempel(11)

4-element Vector{Vector{Integer}}:
 [5, 3, 2, 7, 1, 8, 4, 6, 9]
 [1, 4, 6, 2, 9, 3, 8, 7, 5]
 [2, 1, 5, 8, 3, 9, 7, 4, 6]
 [4, 6, 3, 1, 7, 2, 5, 9, 8]

In [32]:
lempel(11)

4-element Vector{Vector{Integer}}:
 [5, 3, 2, 7, 1, 8, 4, 6, 9]
 [1, 4, 6, 2, 9, 3, 8, 7, 5]
 [2, 1, 5, 8, 3, 9, 7, 4, 6]
 [4, 6, 3, 1, 7, 2, 5, 9, 8]

In [33]:
welch(11)

4-element Vector{Vector{Integer}}:
 [2, 4, 8, 5, 10, 9, 7, 3, 6, 1]
 [6, 3, 7, 9, 10, 5, 8, 4, 2, 1]
 [7, 5, 2, 3, 10, 4, 6, 9, 8, 1]
 [8, 9, 6, 4, 10, 3, 2, 5, 7, 1]

In [35]:
welch(9)

Vector{Integer}[]

In [38]:
Pkg.add("Z3")

   Resolving package versions...
   Installed CEnum ──────────────── v0.5.0
   Installed libcxxwrap_julia_jll ─ v0.13.2+0
   Installed z3_jll ─────────────── v4.13.3+0
   Installed Z3 ─────────────────── v1.0.3
    Updating `~/.julia/environments/v1.10/Project.toml`
  [06b161dc] + Z3 v1.0.3
    Updating `~/.julia/environments/v1.10/Manifest.toml`
  [fa961155] + CEnum v0.5.0
  [06b161dc] + Z3 v1.0.3
  [3eaa8342] + libcxxwrap_julia_jll v0.13.2+0
  [1bc4e1ec] + z3_jll v4.13.3+0
  [781609d7] + GMP_jll v6.2.1+6
Precompiling project...
  ✓ GMP_jll
  ✓ CEnum
  ✓ libcxxwrap_julia_jll
  ✓ z3_jll
  ✓ Z3
  5 dependencies successfully precompiled in 2 seconds. 54 already precompiled.


In [50]:
Z3.FuncDecl()

LoadError: MethodError: no method matching FuncDecl()

Closest candidates are:
  FuncDecl(::Context, ::Ptr{Z3.Libz3._Z3_func_decl})
   @ Z3 ~/.julia/packages/Z3/L6TVj/src/Z3.jl:150
  FuncDecl(::String, ::Vector{Sort}, ::Sort)
   @ Z3 ~/.julia/packages/Z3/L6TVj/src/Z3.jl:174
  FuncDecl(::String, ::Vector{Sort}, ::Sort, ::Any)
   @ Z3 ~/.julia/packages/Z3/L6TVj/src/Z3.jl:174


In [12]:
f1 = Base.Fix1
f2 = Base.Fix2
p2 = x -> y -> (x, y)

#9 (generic function with 1 method)

In [13]:
function isprimitiveroot(prime::Integer, alpha::Integer)::Bool 
    not_one::Bool = all(powermod(alpha, i, prime) != prime - 1 for i in 1:((prime - 1) ÷ 2 - 1))
    last_one::Bool = powermod(alpha, (prime - 1) ÷ 2, prime) == prime - 1
    not_one && last_one
end

isprimitiveroot (generic function with 1 method)

In [6]:
filter(alpha -> isprimitiveroot(13, alpha), 2:13)

4-element Vector{Int64}:
  2
  6
  7
 11

In [5]:
struct Unit
end

struct Pair{T, S}
    l::T
    r::S
    function fst()::T
        l
    end
    function snd()::S
        r
    end
end

# Check if a sequence is a Costas sequence with debug information
function iscostasdbg(lst::Vector, f::Function = normal_predicate) #::Union{Unit, Tuple{Int64, Int64}}
    n::Integer = length(lst)
    for k in 1:n
        diffs = [(false, (-1,-1)) for _ in 1:2 * n]
        for i in 1:(n - k)
            a = lst[i + k]
            b = lst[i]
            result = f(a, b, n)
            if diffs[result][1]
                return ((i, i + k), diffs[result][2])
            elseif result != n
                diffs[result] = (true, (i, i + k))
            end
        end
    end
    return Unit()
end

iscostasdbg (generic function with 2 methods)

In [6]:
using Base.Threads
function searchdbg(n::Integer)::Vector{Vector{Integer}}
    p1 = 0
    p2 = 0
    p3 = 0
    p4 = 0
    i1 = 0
    i2 = 0
    i3 = 0
    i4 = 0
    acc::Vector{Vector{Vector{Integer}}} = [[] for _ in 1:nthreads()]
    
    @threads :static for i in 1:factorial(n)
        tid = threadid()
        lst = nthperm(1:n, i)
        if (i1 != 0 && p1 == lst[i1]) && (i2 != 0 && p2 == lst[i2]) && (i3 != 0 && p3 == lst[i3]) && (i4 != 0 && p4 == lst[i4])
            #println("miss: ", lst)
            continue
        end
        result = iscostasdbg(lst)
        if result isa Unit
            push!(acc[tid], lst)
        else
            #println("fail: ", lst, "; ", result)
            (i1, i2), (i3, i4) = result
            p1, p2, p3, p4 = lst[i1], lst[i2], lst[i3], lst[i4]
        end
    end
    reduce(vcat, acc)
end

searchdbg (generic function with 1 method)

In [231]:
searchdbg(10)

2160-element Vector{Vector{Integer}}:
 [1, 2, 4, 8, 5, 10, 9, 7, 3, 6]
 [1, 2, 5, 7, 3, 10, 9, 6, 4, 8]
 [1, 2, 5, 9, 3, 8, 4, 10, 7, 6]
 [1, 2, 5, 9, 3, 10, 8, 7, 4, 6]
 [1, 2, 6, 9, 8, 5, 7, 3, 10, 4]
 [1, 2, 8, 5, 10, 4, 6, 9, 7, 3]
 [1, 2, 8, 10, 6, 3, 7, 5, 4, 9]
 [1, 2, 9, 3, 5, 10, 8, 4, 7, 6]
 [1, 2, 9, 6, 5, 7, 10, 4, 8, 3]
 [1, 2, 10, 6, 4, 7, 9, 3, 8, 5]
 [1, 2, 10, 8, 5, 4, 6, 9, 3, 7]
 [1, 3, 4, 9, 8, 6, 10, 7, 2, 5]
 [1, 3, 7, 10, 9, 4, 2, 8, 5, 6]
 ⋮
 [10, 8, 7, 2, 3, 5, 1, 4, 9, 6]
 [10, 9, 1, 3, 6, 7, 5, 2, 8, 4]
 [10, 9, 1, 5, 7, 4, 2, 8, 3, 6]
 [10, 9, 2, 5, 6, 4, 1, 7, 3, 8]
 [10, 9, 2, 8, 6, 1, 3, 7, 4, 5]
 [10, 9, 3, 1, 5, 8, 4, 6, 7, 2]
 [10, 9, 3, 6, 1, 7, 5, 2, 4, 8]
 [10, 9, 5, 2, 3, 6, 4, 8, 1, 7]
 [10, 9, 6, 2, 8, 1, 3, 4, 7, 5]
 [10, 9, 6, 2, 8, 3, 7, 1, 4, 5]
 [10, 9, 6, 4, 8, 1, 2, 5, 7, 3]
 [10, 9, 7, 3, 6, 1, 2, 4, 8, 5]

In [209]:
function search(n::Integer)::Vector{Vector{Integer}}
    1:n |> permutations |> Filter(iscostas) |> collect
end

search (generic function with 1 method)

In [211]:
search(10)

2160-element Vector{Vector{Integer}}:
 [1, 2, 4, 8, 5, 10, 9, 7, 3, 6]
 [1, 2, 5, 7, 3, 10, 9, 6, 4, 8]
 [1, 2, 5, 9, 3, 8, 4, 10, 7, 6]
 [1, 2, 5, 9, 3, 10, 8, 7, 4, 6]
 [1, 2, 6, 9, 8, 5, 7, 3, 10, 4]
 [1, 2, 8, 5, 10, 4, 6, 9, 7, 3]
 [1, 2, 8, 10, 6, 3, 7, 5, 4, 9]
 [1, 2, 9, 3, 5, 10, 8, 4, 7, 6]
 [1, 2, 9, 6, 5, 7, 10, 4, 8, 3]
 [1, 2, 10, 6, 4, 7, 9, 3, 8, 5]
 [1, 2, 10, 8, 5, 4, 6, 9, 3, 7]
 [1, 3, 4, 9, 8, 6, 10, 7, 2, 5]
 [1, 3, 7, 10, 9, 4, 2, 8, 5, 6]
 ⋮
 [10, 8, 7, 2, 3, 5, 1, 4, 9, 6]
 [10, 9, 1, 3, 6, 7, 5, 2, 8, 4]
 [10, 9, 1, 5, 7, 4, 2, 8, 3, 6]
 [10, 9, 2, 5, 6, 4, 1, 7, 3, 8]
 [10, 9, 2, 8, 6, 1, 3, 7, 4, 5]
 [10, 9, 3, 1, 5, 8, 4, 6, 7, 2]
 [10, 9, 3, 6, 1, 7, 5, 2, 4, 8]
 [10, 9, 5, 2, 3, 6, 4, 8, 1, 7]
 [10, 9, 6, 2, 8, 1, 3, 4, 7, 5]
 [10, 9, 6, 2, 8, 3, 7, 1, 4, 5]
 [10, 9, 6, 4, 8, 1, 2, 5, 7, 3]
 [10, 9, 7, 3, 6, 1, 2, 4, 8, 5]

In [126]:
for i in 1:6
    println(nthperm([1,2,3], i))
end

[1, 2, 3]
[1, 3, 2]
[2, 1, 3]
[2, 3, 1]
[3, 1, 2]
[3, 2, 1]


In [139]:
lst = [1,2,3]
for i in 1:6
    nthperm!(lst, i)
    println(lst)
end

[1, 2, 3]
[1, 3, 2]
[3, 1, 2]
[1, 2, 3]
[3, 1, 2]
[2, 1, 3]


In [213]:
@btime search(10)

  1.484 s (36471369 allocations: 4.23 GiB)


2160-element Vector{Vector{Integer}}:
 [1, 2, 4, 8, 5, 10, 9, 7, 3, 6]
 [1, 2, 5, 7, 3, 10, 9, 6, 4, 8]
 [1, 2, 5, 9, 3, 8, 4, 10, 7, 6]
 [1, 2, 5, 9, 3, 10, 8, 7, 4, 6]
 [1, 2, 6, 9, 8, 5, 7, 3, 10, 4]
 [1, 2, 8, 5, 10, 4, 6, 9, 7, 3]
 [1, 2, 8, 10, 6, 3, 7, 5, 4, 9]
 [1, 2, 9, 3, 5, 10, 8, 4, 7, 6]
 [1, 2, 9, 6, 5, 7, 10, 4, 8, 3]
 [1, 2, 10, 6, 4, 7, 9, 3, 8, 5]
 [1, 2, 10, 8, 5, 4, 6, 9, 3, 7]
 [1, 3, 4, 9, 8, 6, 10, 7, 2, 5]
 [1, 3, 7, 10, 9, 4, 2, 8, 5, 6]
 ⋮
 [10, 8, 7, 2, 3, 5, 1, 4, 9, 6]
 [10, 9, 1, 3, 6, 7, 5, 2, 8, 4]
 [10, 9, 1, 5, 7, 4, 2, 8, 3, 6]
 [10, 9, 2, 5, 6, 4, 1, 7, 3, 8]
 [10, 9, 2, 8, 6, 1, 3, 7, 4, 5]
 [10, 9, 3, 1, 5, 8, 4, 6, 7, 2]
 [10, 9, 3, 6, 1, 7, 5, 2, 4, 8]
 [10, 9, 5, 2, 3, 6, 4, 8, 1, 7]
 [10, 9, 6, 2, 8, 1, 3, 4, 7, 5]
 [10, 9, 6, 2, 8, 3, 7, 1, 4, 5]
 [10, 9, 6, 4, 8, 1, 2, 5, 7, 3]
 [10, 9, 7, 3, 6, 1, 2, 4, 8, 5]

In [214]:
@btime searchdbg(10)

  457.476 ms (4579564 allocations: 990.79 MiB)


2160-element Vector{Vector{Integer}}:
 [1, 2, 4, 8, 5, 10, 9, 7, 3, 6]
 [1, 2, 5, 7, 3, 10, 9, 6, 4, 8]
 [1, 2, 5, 9, 3, 8, 4, 10, 7, 6]
 [1, 2, 5, 9, 3, 10, 8, 7, 4, 6]
 [1, 2, 6, 9, 8, 5, 7, 3, 10, 4]
 [1, 2, 8, 5, 10, 4, 6, 9, 7, 3]
 [1, 2, 8, 10, 6, 3, 7, 5, 4, 9]
 [1, 2, 9, 3, 5, 10, 8, 4, 7, 6]
 [1, 2, 9, 6, 5, 7, 10, 4, 8, 3]
 [1, 2, 10, 6, 4, 7, 9, 3, 8, 5]
 [1, 2, 10, 8, 5, 4, 6, 9, 3, 7]
 [1, 3, 4, 9, 8, 6, 10, 7, 2, 5]
 [1, 3, 7, 10, 9, 4, 2, 8, 5, 6]
 ⋮
 [10, 8, 7, 2, 3, 5, 1, 4, 9, 6]
 [10, 9, 1, 3, 6, 7, 5, 2, 8, 4]
 [10, 9, 1, 5, 7, 4, 2, 8, 3, 6]
 [10, 9, 2, 5, 6, 4, 1, 7, 3, 8]
 [10, 9, 2, 8, 6, 1, 3, 7, 4, 5]
 [10, 9, 3, 1, 5, 8, 4, 6, 7, 2]
 [10, 9, 3, 6, 1, 7, 5, 2, 4, 8]
 [10, 9, 5, 2, 3, 6, 4, 8, 1, 7]
 [10, 9, 6, 2, 8, 1, 3, 4, 7, 5]
 [10, 9, 6, 2, 8, 3, 7, 1, 4, 5]
 [10, 9, 6, 4, 8, 1, 2, 5, 7, 3]
 [10, 9, 7, 3, 6, 1, 2, 4, 8, 5]

In [216]:
zeros([], factorial(4))

LoadError: MethodError: no method matching zeros(::Vector{Any}, ::Int64)

Closest candidates are:
  zeros(::Union{Integer, AbstractUnitRange}...)
   @ Base array.jl:631
  zeros(::Type{T}, ::Union{Integer, AbstractUnitRange}...) where T
   @ Base array.jl:632


In [15]:
using Base.Threads
function searchone(n::Integer)::Union{Nothing, Vector{Integer}}
    p1 = 0
    p2 = 0
    p3 = 0
    p4 = 0
    i1 = 0
    i2 = 0
    i3 = 0
    i4 = 0
    
    for i in 1:factorial(n)
        lst = nthperm(1:n, i)
        if (i1 != 0 && p1 == lst[i1]) && (i2 != 0 && p2 == lst[i2]) && (i3 != 0 && p3 == lst[i3]) && (i4 != 0 && p4 == lst[i4])
            continue
        end
        result = iscostasdbg(lst)
        if result isa Unit
            return lst
        else
            (i1, i2), (i3, i4) = result
            p1, p2, p3, p4 = lst[i1], lst[i2], lst[i3], lst[i4]
        end
    end
    return nothing
end

searchone (generic function with 1 method)

In [13]:
@btime searchone(10)

  1.959 ms (8464 allocations: 1.27 MiB)


In [26]:
v14 = searchone(14)

14-element Vector{Integer}:
  1
  2
  5
  7
 14
  8
 12
 11
  6
  4
 13
 10
  3
  9

In [27]:
buildallnaive(v14, 15)

Vector{Integer}[]

In [32]:
iscostas([5,3,2,4,1,6])

true

In [33]:
primes(39)

12-element Vector{Int64}:
  2
  3
  5
  7
 11
 13
 17
 19
 23
 29
 31
 37

In [38]:
function lempelc(prime::Integer, c::Integer = 1)::Vector{Vector{Integer}}
    welch(prime) .|> lst -> init(lst) .|> n -> findindex(lst, prime + c - n)
end

lempelc (generic function with 2 methods)

lempelc(37)

In [52]:
for p in primes(40)
    flag = false
    for l in lempel(p)
        if l |> f2(vcat, p) |> iscostas
            flag = true
        end
        if flag
            break
        end
    end
    println("$(p): $(flag)")
end

2: true
3: true
5: true
7: true
11: false
13: false
17: true
19: true
23: false
29: false
31: false
37: false


In [ ]:
searchone(20)